export const THEMES = [
  {
    id: 'minimal-gray',
    name: 'Minimal Gray',
    swatches: ['#bcc3ce', '#4a5568'],
    vars: {
      '--theme-gradient': 'linear-gradient(160deg, #dfe3ea 0%, #c8cfd8 100%)',
      '--theme-bg-fallback': '#dfe3ea',
      '--theme-card-bg': '#ffffff',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.08)',
      '--theme-today-dot': '#3d4551',
      '--theme-accent': '#4a5568',
      '--theme-accent-hover': '#3d4551',
      '--theme-task-bg': '#f5f6f8',
      '--theme-task-bg-hover': '#eceef2',
      '--theme-checkbox-border': '#c0c7d1',
      '--theme-checkbox-fill': '#4a5568',
      '--theme-text': '#1a1a1a',
      '--theme-text-secondary': '#6b6b6b',
      '--theme-text-muted': '#a0a0a0',
      '--theme-surface': '#ffffff',
      '--theme-border': '#e0e4ea',
      '--theme-border-light': '#f0f2f5',
      '--theme-card-text': '#1a1a1a',
    },
  },
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    swatches: ['#4a90d9', '#3abdb0'],
    vars: {
      '--theme-gradient': 'linear-gradient(135deg, #4a90d9 0%, #3abdb0 100%)',
      '--theme-bg-fallback': '#4a90d9',
      '--theme-card-bg': '#ffffff',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.12)',
      '--theme-today-dot': '#2563eb',
      '--theme-accent': '#2563eb',
      '--theme-accent-hover': '#1d4ed8',
      '--theme-task-bg': '#EBF0FF',
      '--theme-task-bg-hover': '#DBEAFE',
      '--theme-checkbox-border': '#2563eb',
      '--theme-checkbox-fill': '#2563eb',
      '--theme-text': '#1a1a1a',
      '--theme-text-secondary': '#6b6b6b',
      '--theme-text-muted': '#a0a0a0',
      '--theme-surface': '#ffffff',
      '--theme-border': '#e5e5e5',
      '--theme-border-light': '#f0f0f0',
      '--theme-card-text': '#1a1a1a',
    },
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    swatches: ['#f6d365', '#fda085'],
    vars: {
      '--theme-gradient': 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)',
      '--theme-bg-fallback': '#f6d365',
      '--theme-card-bg': '#ffffff',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.08)',
      '--theme-today-dot': '#ea580c',
      '--theme-accent': '#ea580c',
      '--theme-accent-hover': '#c2410c',
      '--theme-task-bg': '#FFF4ED',
      '--theme-task-bg-hover': '#FFEDD5',
      '--theme-checkbox-border': '#ea580c',
      '--theme-checkbox-fill': '#ea580c',
      '--theme-text': '#1a1a1a',
      '--theme-text-secondary': '#6b6b6b',
      '--theme-text-muted': '#a0a0a0',
      '--theme-surface': '#ffffff',
      '--theme-border': '#e5e5e5',
      '--theme-border-light': '#f0f0f0',
      '--theme-card-text': '#1a1a1a',
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    swatches: ['#a8e6cf', '#88d8a8'],
    vars: {
      '--theme-gradient': 'linear-gradient(135deg, #a8e6cf 0%, #88d8a8 100%)',
      '--theme-bg-fallback': '#a8e6cf',
      '--theme-card-bg': '#ffffff',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.08)',
      '--theme-today-dot': '#16a34a',
      '--theme-accent': '#16a34a',
      '--theme-accent-hover': '#15803d',
      '--theme-task-bg': '#ECFDF5',
      '--theme-task-bg-hover': '#D1FAE5',
      '--theme-checkbox-border': '#16a34a',
      '--theme-checkbox-fill': '#16a34a',
      '--theme-text': '#1a1a1a',
      '--theme-text-secondary': '#6b6b6b',
      '--theme-text-muted': '#a0a0a0',
      '--theme-surface': '#ffffff',
      '--theme-border': '#e5e5e5',
      '--theme-border-light': '#f0f0f0',
      '--theme-card-text': '#1a1a1a',
    },
  },
  {
    id: 'purple-dream',
    name: 'Purple Dream',
    swatches: ['#c3b1e1', '#a855f7'],
    vars: {
      '--theme-gradient': 'linear-gradient(135deg, #c3b1e1 0%, #a855f7 100%)',
      '--theme-bg-fallback': '#c3b1e1',
      '--theme-card-bg': '#ffffff',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.08)',
      '--theme-today-dot': '#9333ea',
      '--theme-accent': '#9333ea',
      '--theme-accent-hover': '#7e22ce',
      '--theme-task-bg': '#F5F0FF',
      '--theme-task-bg-hover': '#EDE9FE',
      '--theme-checkbox-border': '#9333ea',
      '--theme-checkbox-fill': '#9333ea',
      '--theme-text': '#1a1a1a',
      '--theme-text-secondary': '#6b6b6b',
      '--theme-text-muted': '#a0a0a0',
      '--theme-surface': '#ffffff',
      '--theme-border': '#e5e5e5',
      '--theme-border-light': '#f0f0f0',
      '--theme-card-text': '#1a1a1a',
    },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    swatches: ['#e8b89d', '#d4956b'],
    vars: {
      '--theme-gradient': 'linear-gradient(135deg, #f0cdb4 0%, #e8b89d 100%)',
      '--theme-bg-fallback': '#e8b89d',
      '--theme-card-bg': '#ffffff',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.08)',
      '--theme-today-dot': '#c87f4a',
      '--theme-accent': '#c87f4a',
      '--theme-accent-hover': '#b5703f',
      '--theme-task-bg': '#fdf6f0',
      '--theme-task-bg-hover': '#faeee3',
      '--theme-checkbox-border': '#d4a880',
      '--theme-checkbox-fill': '#c87f4a',
      '--theme-text': '#1a1a1a',
      '--theme-text-secondary': '#6b6b6b',
      '--theme-text-muted': '#a0a0a0',
      '--theme-surface': '#ffffff',
      '--theme-border': '#ecddd0',
      '--theme-border-light': '#f5ede5',
      '--theme-card-text': '#1a1a1a',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    swatches: ['#1a2744', '#3b82f6'],
    vars: {
      '--theme-gradient': 'linear-gradient(160deg, #0f1729 0%, #1a2744 50%, #1e3a5f 100%)',
      '--theme-bg-fallback': '#0f1729',
      '--theme-card-bg': '#1a2744',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.4)',
      '--theme-today-dot': '#3b82f6',
      '--theme-accent': '#3b82f6',
      '--theme-accent-hover': '#2563eb',
      '--theme-task-bg': '#243352',
      '--theme-task-bg-hover': '#2d3f63',
      '--theme-checkbox-border': '#3b82f6',
      '--theme-checkbox-fill': '#3b82f6',
      '--theme-text': '#e8edf5',
      '--theme-text-secondary': '#8899b4',
      '--theme-text-muted': '#5a6d8a',
      '--theme-surface': '#1a2744',
      '--theme-border': '#2d3f63',
      '--theme-border-light': '#1f2f4d',
      '--theme-card-text': '#f1f5f9',
    },
  },
  {
    id: 'cherry-red',
    name: 'Cherry Red',
    swatches: ['#dc2626', '#fca5a5'],
    vars: {
      '--theme-gradient': 'linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)',
      '--theme-bg-fallback': '#fef2f2',
      '--theme-card-bg': '#ffffff',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.08)',
      '--theme-today-dot': '#dc2626',
      '--theme-accent': '#dc2626',
      '--theme-accent-hover': '#b91c1c',
      '--theme-task-bg': '#FEF2F2',
      '--theme-task-bg-hover': '#FEE2E2',
      '--theme-checkbox-border': '#dc2626',
      '--theme-checkbox-fill': '#dc2626',
      '--theme-text': '#1a1a1a',
      '--theme-text-secondary': '#6b6b6b',
      '--theme-text-muted': '#a0a0a0',
      '--theme-surface': '#ffffff',
      '--theme-border': '#e5e5e5',
      '--theme-border-light': '#f0f0f0',
      '--theme-card-text': '#1a1a1a',
    },
  },
  {
    id: 'blue-steel',
    name: 'Blue Steel',
    swatches: ['#2c3e57', '#7b8fa8'],
    vars: {
      '--theme-gradient': 'linear-gradient(160deg, #1e2b3d 0%, #2c3e57 50%, #3a506b 100%)',
      '--theme-bg-fallback': '#1e2b3d',
      '--theme-card-bg': '#283848',
      '--theme-card-shadow': '0 8px 32px rgba(0,0,0,0.35)',
      '--theme-today-dot': '#7b8fa8',
      '--theme-accent': '#7b8fa8',
      '--theme-accent-hover': '#6a7e97',
      '--theme-task-bg': '#334a60',
      '--theme-task-bg-hover': '#3d5570',
      '--theme-checkbox-border': '#7b8fa8',
      '--theme-checkbox-fill': '#7b8fa8',
      '--theme-text': '#e2e8f0',
      '--theme-text-secondary': '#9baab9',
      '--theme-text-muted': '#6b7f94',
      '--theme-surface': '#283848',
      '--theme-border': '#3d5570',
      '--theme-border-light': '#2e4258',
      '--theme-card-text': '#e2e8f0',
    },
  },
];

export const DEFAULT_THEME_ID = 'minimal-gray';

export function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}
